'''
06_data_wrangling.py - collects genomad, pharokka, and defensefinder outputs into tidy tables for analysis
Mostly just data shuffling - only calculation required is determining whether defense/anti-defense 
elements fall inside a prophage.

Run from project root directory with: conda run -n kp-tools python scripts/06_data_wrangling.py

Outputs (in results/tables/):
    prophages.tsv               -   one row per prophage
    prophage_genes.tsv          -   one row per prophage CDS
    defense_systems.tsv         -   one row per defense/anti-defense system
    defense_system_genes.tsv    -   one row per defense/anti-defense gene
    samples.tsv                 -   one row per genome
'''

from pathlib import Path
import sys
import pandas as pd


# --- Configuration settings ---
ACCESSIONS = Path("data/accession_selected.txt")
GENOMAD_DIR = Path("results/genomad")
PHAROKKA_DIR = Path("results/pharokka")
DEFENSE_DIR = Path("results/defensefinder")
MLST_FILE = Path("results/mlst/mlst.tsv")
OUT_DIR = Path("results/tables")


# --- Helper functions ---

# Function to read .tsv files, returning an empty df for files which don't exist (e.g. pharokka with no prophages)
def read_tsv(path, missing_ok = False):
    if not path.exists():
        if missing_ok:
            return pd.DataFrame()
        sys.exit(f"ERROR: expected file not found: {path}")
        
    tsv = pd.read_csv(path, sep = "\t")
    return tsv


# Function to concatenate a list of dataframes and write to a .tsv
def write(frames, name):
    if frames:
        table = pd.concat(frames, ignore_index = True)
        table.to_csv(OUT_DIR/name, sep = "\t", index = False)
        print(f"Wrote {OUT_DIR/name} ({len(table)} rows)")
    else:
        print(f"No data for {name}")


# --- 1. Prophages (from genomad) ---
def get_prophages(sample):
    path = GENOMAD_DIR/sample/f"{sample}_find_proviruses"/f"{sample}_provirus.tsv"
    tsv = read_tsv(path)

    tsv.insert(0, "sample", sample)
    return tsv


# --- 2. Prophage genes (from pharokka) ---

# Script 04 skips pharokka if no prophages were found, so missing_ok is set to True.
def get_prophage_genes(sample):
    path = PHAROKKA_DIR/sample/"pharokka_cds_final_merged_output.tsv"
    tsv = read_tsv(path, missing_ok = True)

    # contig is the prophage name
    tsv.insert(0, "sample", sample)
    tsv = tsv.rename(columns = {"contig" : "prophage"})
    return tsv


# --- 3. Defense/anti-defense systems (from defensefinder) ---

# Map protein IDs in genome to contig & coordiantes to check prophage locations against genes
# Defensefinder ran on protein output generated by genomad -> identical contig IDs
def get_gene_coordinates(sample):
    path = GENOMAD_DIR/sample/f"{sample}_annotate"/f"{sample}_genes.tsv"
    tsv = read_tsv(path)

    if not {"gene", "start", "end"}.issubset(tsv.columns):
        sys.exit(f"ERROR: {path} lacks expected columns (gene/start/end)."
                 f"Found: {list(tsv.columns)}")

    coordinates = tsv[["gene", "start", "end"]]
    coordinates["contig"] = coordinates["gene"].str.rsplit("_", n = 1).str[0]
    return coordinates


# Determine if the gene is in a prophage & which one using the gene coordinates
# Testing on midpoint - means no need for strict containment against possibly-off predictions
def locate_in_prophage(contig, start, end, prophages):

    midpoint = (start + end) / 2
    on_contig = prophages[prophages["source_seq"] == contig]

    # This loop assumes identified prophages cannot overlap - check pharokka process to see if overlap is possible 
    # (e.g. for nested/tandem phages)
    for _, prophage in on_contig.iterrows():
        if prophage["start"] <= midpoint <= prophage["end"]:
            return prophage["seq_name"]

    return None


# Defensefinder returns results by system in the *_systems.tsv, located by protein ID (no coordinates)
# Genes are located in *_genes.tsv. Genes therefore used to get location of systems
def get_defense_systems(sample, prophages):
    base = DEFENSE_DIR/sample
    systems = read_tsv(base/f"{sample}_proteins_defense_finder_systems.tsv")
    genes = read_tsv(base/f"{sample}_proteins_defense_finder_genes.tsv")


    coords = get_gene_coordinates(sample)
    coords = coords.rename(columns = {"gene": "hit_id"})

    genes = genes.merge(coords, on = "hit_id", how = "left")

    unplaced = (genes[genes["start"].isna() | genes["end"].isna()])
    if len(unplaced):
        ids = ", ".join(unplaced["hit_id"])
        print(f"WARNING: {len(unplaced)} defense genes could not be assigned coordinates")
        print(f"IDs: {ids}")

    genes["prophage"] = [locate_in_prophage(row["contig"], row["start"], row["end"], prophages)
                         for _, row in genes.iterrows()]
    genes["in_prophage"] = genes["prophage"].notna()
    genes.insert(0, "sample", sample)

    # If any genes in a system is encoded by a phage, we will call that system phage-encoded
    by_system = (genes.groupby("sys_id").agg(in_prophage=("in_prophage", "any"), # TRUE if any gene is in_prophage
                                             # Returns string of all unique prophages in the system
                                             prophage = ("prophage", lambda s: 
                                                         ";".join(sorted(s.dropna().unique())) or None))
                                                         .reset_index() # groupby sets sys_id to index; reset to col.
    )

    systems = systems.merge(by_system, on = "sys_id", how = "left")
    systems.insert(0, "sample", sample)

    return systems, genes


# --- 4. Main ---
def main():
    if not ACCESSIONS.exists():
        sys.exit(f"ERROR: {ACCESSIONS} not found")

    samples = ACCESSIONS.read_text().split()
    print(f"Wrangling {len(samples)} samples...")

    OUT_DIR.mkdir(parents = True, exist_ok = True)

    all_prophages = []
    all_genes = []
    all_systems = []
    all_defense_genes = []
    summary_rows = []

    for sample in samples:
        print(f"\n{sample}")

        prophages = get_prophages(sample)
        n_prophages = len(prophages)
        print(f"{sample} contains {n_prophages} prophages")
        all_prophages.append(prophages)

        genes = get_prophage_genes(sample)
        n_prophage_cds = len(genes)
        print(f"Prophages in {sample} contain {n_prophage_cds} coding sequences")
        all_genes.append(genes)

        systems, defense_genes = get_defense_systems(sample, prophages)
        n_systems = len(systems)
        n_systems_in_prophages = systems["in_prophage"].sum()
        print(f"{sample} defense systems: {n_systems} ({n_systems_in_prophages} prophage-encoded)")

        unmatched = systems["in_prophage"].isna().sum()
        if unmatched:
            print(f"WARNING: {unmatched} systems could not be located")
        
        all_systems.append(systems)
        all_defense_genes.append(defense_genes)

        summary_rows.append({
            "sample": sample,
            "n_prophages": n_prophages,
            "n_prophage_cds": n_prophage_cds,
            "n_defense_systems": n_systems,
            "n_defense_in_prophage": n_systems_in_prophages
        })

    # --- Write tables ---
    print("\n Writing...")
    
    write(all_prophages, "prophages.tsv")
    write(all_genes, "prophage_genes.tsv")
    write(all_systems, "defense_systems.tsv")
    write(all_defense_genes, "defense_genes.tsv")

    summary = pd.DataFrame(summary_rows)

    # Attach ST from MLST so we can analyse by strain
    if not MLST_FILE.exists():
        sys.exit(f"ERROR: MLST file could not be found at {MLST_FILE}")

    mlst = pd.read_csv(MLST_FILE, sep = "\t", header = None)
    mlst = mlst.rename(columns = {0 : "file", 2 : "st"})
    mlst["sample"] = mlst["file"].apply(lambda s: Path(s).stem) # Strip directory and suffix from file names
    summary = summary.merge(mlst[["sample", "st"]], on = "sample", how = "left")

    missing_st = summary["st"].isna().sum()
    if missing_st:
        print(f"WARNING: {missing_st} samples had no MLST match. Check MLST path stripping.")

    summary.to_csv(OUT_DIR/"samples.tsv", sep = "\t", index = False)
    print(f"Wrote {OUT_DIR/'samples.tsv'} ({len(summary)} rows)")

    print("\n--- Summary ---")
    print(summary.to_string(index = False))


if __name__ == "__main__":
    main()